# Generated by Django 5.0.6 on 2024-06-09 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=75)),
                ("phone", models.TextField(blank=True, null=True)),
                ("address", models.TextField(max_length=125)),
            ],
        ),
        migrations.AddField(
            model_name="profile",
            name="is_teacher",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.school",
            ),
        ),
    ]
