# Generated by Django 5.0.6 on 2024-05-17 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("photos", "0004_alter_photo_photographer_alter_photo_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="Photographer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="photos.photographer",
            ),
        ),
    ]
