# Generated by Django 5.0.6 on 2024-05-17 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("photos", "0005_alter_photo_photographer"),
    ]

    operations = [
        migrations.RenameField(
            model_name="photo",
            old_name="CompositionCount",
            new_name="compositionCount",
        ),
        migrations.RemoveField(
            model_name="photo",
            name="Photographer",
        ),
        migrations.AddField(
            model_name="photo",
            name="photographer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="photos.photographer",
            ),
        ),
    ]
