# Generated by Django 5.0.6 on 2024-05-29 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("photos", "0006_rename_compositioncount_photo_compositioncount_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="photographer",
            old_name="introduction",
            new_name="bio",
        ),
        migrations.AddField(
            model_name="photographer",
            name="image",
            field=models.ImageField(null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="photo",
            name="photographer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="photoss",
                to="photos.photographer",
            ),
        ),
    ]
