# Generated by Django 5.0.6 on 2024-05-29 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("photos", "0007_rename_introduction_photographer_bio_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="photographer",
            name="artist_name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="photo",
            name="photographer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="photos",
                to="photos.photographer",
            ),
        ),
    ]
