# Generated by Django 5.0.6 on 2024-05-30 05:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("photos", "0011_alter_photographer_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="photo",
            old_name="desctiption",
            new_name="description",
        ),
    ]
