# Generated by Django 5.0.6 on 2024-05-31 14:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("photos", "0012_rename_desctiption_photo_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="image",
            field=models.ImageField(upload_to="images/"),
        ),
    ]
