# Generated by Django 5.0.6 on 2024-06-09 16:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dad_joke", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Favorite",
            new_name="FavoriteJoke",
        ),
    ]
