# Generated by Django 5.0.6 on 2024-05-17 09:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("photos", "0003_photo_compositioncount_photo_desctiption_and_more"),
        ("writing_exercise", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Composition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("datetime", models.DateTimeField(default=django.utils.timezone.now)),
                ("is_solved", models.BooleanField(default=False)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "photo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="photos.photo"
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="comment",
            name="commenting_to",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="writing_exercise.composition",
            ),
        ),
        migrations.DeleteModel(
            name="Answer",
        ),
    ]
