# Generated by Django 5.0.6 on 2024-05-22 08:03

import django.db.models.deletion
import django.utils.timezone
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("writing_exercise", "0002_composition_alter_comment_commenting_to_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="commenting_to",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="commenting_to",
                to="writing_exercise.composition",
            ),
        ),
        migrations.CreateModel(
            name="Reply",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
                ),
                ("datetime", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "reply_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="writing_exercise.comment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
