# Generated by Django 5.0.6 on 2024-05-23 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("writing_exercise", "0003_alter_comment_commenting_to_reply"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reply",
            name="reply_to",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="writing_exercise.comment",
            ),
        ),
    ]
