# Generated by Django 5.0.6 on 2024-05-25 09:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("writing_exercise", "0005_alter_comment_options_comment_parent_delete_reply"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="datetime",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
